### ISSUE TITLE
Plugin not working on android build

### ISSUE THREAD

**Issue by braianj** [gitawego/cordova-screenshot#47]
Hello, with ios build it's ok.
But with android build return

```
-compile:
    [javac] Compiling 3 source files to /Users/.../.../Weather/Proyecto/Que Onda/platforms/android/ant-build/classes
    [javac] /Users/.../.../Weather/Proyecto/Que Onda/platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:71: cannot find symbol
    [javac] symbol  : method getView()
    [javac] location: class org.apache.cordova.CordovaWebView
    [javac] 				TextureView textureView = findXWalkTextureView((ViewGroup)webView.getView());
    [javac] 				                                                                 ^
    [javac] 1 error

BUILD FAILED
/Users/.../XXX/Android SDK/adt-bundle-mac-x86_64-20140702/sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/Users/.../XXX/Android SDK/adt-bundle-mac-x86_64-20140702/sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 2 seconds

/Users/.../.../Weather/Proyecto/Que Onda/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/Users/.../.../Weather/Proyecto/Que Onda/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
ERROR building one of the platforms: Error: /Users/.../.../Weather/Proyecto/Que Onda/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
```

After cordova plugin rm com.darktalker.cordova.screenshot it works again.

Ideas?

**Comment by gitawego** [comment]
could you tell me which version of cordova are u using ? have u upgraded your android platefome to the latest version ?

**Comment by braianj** [comment]
Cordova version: 4.2.0
![captura de pantalla 2015-05-07 a las 18 20 33](https://cloud.githubusercontent.com/assets/6572776/7526153/ca73b46a-f4e5-11e4-925b-785d49ba9737.png)

**Comment by theAmazingEngineer** [comment]
hello, i had the same problem
i updated my phonegap version from Npm (sudo npm update -g  phonegap)
and update android platform (phonegap platform update android)
and it works.

**Comment by braianj** [comment]
Hi @theAmazingEngineer 
Thanks for your answer, but after doing the update, and after lot of hour trying to update the java, los of new error show as new

```
$ cordova build android
Running command: "/Users/.../platforms/android/cordova/build" 
ANDROID_HOME=/Users/braianmellor/Trabajo/Android SDK/adt-bundle-mac-x86_64-20140702/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
Running: /Users/.../platforms/android/gradlew cdvBuildDebug -b /Users/.../platforms/android/build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava
/Users/.../platforms/android/src/com/candymedia/wasaclima/CordovaApp.java:25: error: cannot find symbol
public class CordovaApp extends CordovaActivity
                                ^
  symbol: class CordovaActivity
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:16: error: cannot find symbol
import org.apache.cordova.CallbackContext;
                         ^
  symbol:   class CallbackContext
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:17: error: cannot find symbol
import org.apache.cordova.CordovaPlugin;
                         ^
  symbol:   class CordovaPlugin
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:18: error: cannot find symbol
import org.apache.cordova.PluginResult;
                         ^
  symbol:   class PluginResult
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:34: error: cannot find symbol
public class Screenshot extends CordovaPlugin {
                                ^
  symbol: class CordovaPlugin
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:99: error: cannot find symbol
	public boolean execute(String action, JSONArray args, final CallbackContext callbackContext) throws JSONException {
	                                                            ^
  symbol:   class CallbackContext
  location: class Screenshot
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:26: error: package com.rjfun.cordova.ad does not exist
import com.rjfun.cordova.ad.GenericAdPlugin;
                           ^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:28: error: cannot find symbol
public class AdMobPlugin extends GenericAdPlugin {
                                 ^
  symbol: class GenericAdPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/ext/CordovaPluginExt.java:5: error: cannot find symbol
import org.apache.cordova.CallbackContext;
                         ^
  symbol:   class CallbackContext
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/rjfun/cordova/ext/CordovaPluginExt.java:6: error: cannot find symbol
import org.apache.cordova.CordovaPlugin;
                         ^
  symbol:   class CordovaPlugin
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/rjfun/cordova/ext/CordovaPluginExt.java:7: error: cannot find symbol
import org.apache.cordova.CordovaWebView;
                         ^
  symbol:   class CordovaWebView
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/rjfun/cordova/ext/CordovaPluginExt.java:8: error: cannot find symbol
import org.apache.cordova.PluginResult;
                         ^
  symbol:   class PluginResult
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/rjfun/cordova/ext/CordovaPluginExt.java:13: error: cannot find symbol
public class CordovaPluginExt extends CordovaPlugin implements PluginAdapterDelegate {
                                      ^
  symbol: class CordovaPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/ext/PluginAdapterDelegate.java:3: error: cannot find symbol
import org.apache.cordova.CallbackContext;
                         ^
  symbol:   class CallbackContext
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/rjfun/cordova/ext/PluginAdapterDelegate.java:4: error: cannot find symbol
import org.apache.cordova.PluginResult;
                         ^
  symbol:   class PluginResult
  location: package org.apache.cordova
/Users/.../platforms/android/src/com/rjfun/cordova/ext/CordovaPluginExt.java:74: error: cannot find symbol
	public void sendPluginResult(PluginResult result, CallbackContext context) {
	                             ^
  symbol:   class PluginResult
  location: class CordovaPluginExt
/Users/.../platforms/android/src/com/rjfun/cordova/ext/CordovaPluginExt.java:74: error: cannot find symbol
	public void sendPluginResult(PluginResult result, CallbackContext context) {
	                                                  ^
  symbol:   class CallbackContext
  location: class CordovaPluginExt
/Users/.../platforms/android/src/com/rjfun/cordova/ext/PluginAdapterDelegate.java:18: error: cannot find symbol
	public void sendPluginResult(PluginResult result, CallbackContext context);
	                             ^
  symbol:   class PluginResult
  location: interface PluginAdapterDelegate
/Users/.../platforms/android/src/com/rjfun/cordova/ext/PluginAdapterDelegate.java:18: error: cannot find symbol
	public void sendPluginResult(PluginResult result, CallbackContext context);
	                                                  ^
  symbol:   class CallbackContext
  location: interface PluginAdapterDelegate
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:15: error: cannot find symbol
import org.apache.cordova.CallbackContext;
                         ^
  symbol:   class CallbackContext
  location: package org.apache.cordova
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:16: error: cannot find symbol
import org.apache.cordova.CordovaInterface;
                         ^
  symbol:   class CordovaInterface
  location: package org.apache.cordova
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:17: error: cannot find symbol
import org.apache.cordova.CordovaPlugin;
                         ^
  symbol:   class CordovaPlugin
  location: package org.apache.cordova
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:18: error: cannot find symbol
import org.apache.cordova.PluginResult;
                         ^
  symbol:   class PluginResult
  location: package org.apache.cordova
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:34: error: cannot find symbol
public class SocialSharing extends CordovaPlugin {
                                   ^
  symbol: class CordovaPlugin
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:50: error: cannot find symbol
  private CallbackContext _callbackContext;
          ^
  symbol:   class CallbackContext
  location: class SocialSharing
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:62: error: cannot find symbol
  public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
                                                        ^
  symbol:   class CallbackContext
  location: class SocialSharing
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:106: error: cannot find symbol
  private boolean invokeEmailIntent(final CallbackContext callbackContext, final String message, final String subject, final JSONArray to, final JSONArray cc, final JSONArray bcc, final JSONArray files) throws JSONException {
                                          ^
  symbol:   class CallbackContext
  location: class SocialSharing
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:168: error: cannot find symbol
  private boolean doSendIntent(final CallbackContext callbackContext, final String msg, final String subject, final JSONArray files, final String url, final String appPackageName, final boolean peek) {
                                     ^
  symbol:   class CallbackContext
  location: class SocialSharing
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:334: error: cannot find symbol
  private boolean invokeSMSIntent(final CallbackContext callbackContext, JSONObject options, String p_phonenumbers) {
                                        ^
  symbol:   class CallbackContext
  location: class SocialSharing
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:391: error: cannot find symbol
  private ActivityInfo getActivity(final CallbackContext callbackContext, final Intent shareIntent, final String appPackageName) {
                                         ^
  symbol:   class CallbackContext
  location: class SocialSharing
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:55: error: cannot find symbol
    public CallbackContext callbackContext;
           ^
  symbol:   class CallbackContext
  location: class SocialSharing.SocialSharingRunnable
/Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java:56: error: cannot find symbol
    SocialSharingRunnable(CallbackContext cb) {
                          ^
  symbol:   class CallbackContext
  location: class SocialSharing.SocialSharingRunnable
/Users/.../platforms/android/src/org/apache/cordova/camera/CameraLauncher.java:29: error: cannot find symbol
import org.apache.cordova.CallbackContext;
                         ^
  symbol:   class CallbackContext
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/camera/CameraLauncher.java:30: error: cannot find symbol
import org.apache.cordova.CordovaPlugin;
                         ^
  symbol:   class CordovaPlugin
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/camera/CameraLauncher.java:31: error: cannot find symbol
import org.apache.cordova.LOG;
                         ^
  symbol:   class LOG
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/camera/CameraLauncher.java:32: error: cannot find symbol
import org.apache.cordova.PluginResult;
                         ^
  symbol:   class PluginResult
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/camera/CameraLauncher.java:59: error: cannot find symbol
public class CameraLauncher extends CordovaPlugin implements MediaScannerConnectionClient {
                                    ^
  symbol: class CordovaPlugin
/Users/.../platforms/android/src/org/apache/cordova/camera/CameraLauncher.java:93: error: cannot find symbol
    public CallbackContext callbackContext;
           ^
  symbol:   class CallbackContext
  location: class CameraLauncher
/Users/.../platforms/android/src/org/apache/cordova/camera/CameraLauncher.java:108: error: cannot find symbol
    public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
                                                          ^
  symbol:   class CallbackContext
  location: class CameraLauncher
/Users/.../platforms/android/src/org/apache/cordova/camera/FileHelper.java:29: error: cannot find symbol
import org.apache.cordova.CordovaInterface;
                         ^
  symbol:   class CordovaInterface
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/camera/FileHelper.java:30: error: cannot find symbol
import org.apache.cordova.LOG;
                         ^
  symbol:   class LOG
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/camera/FileHelper.java:50: error: cannot find symbol
    public static String getRealPath(Uri uri, CordovaInterface cordova) {
                                              ^
  symbol:   class CordovaInterface
  location: class FileHelper
/Users/.../platforms/android/src/org/apache/cordova/camera/FileHelper.java:75: error: cannot find symbol
    public static String getRealPath(String uriString, CordovaInterface cordova) {
                                                       ^
  symbol:   class CordovaInterface
  location: class FileHelper
/Users/.../platforms/android/src/org/apache/cordova/camera/FileHelper.java:153: error: cannot find symbol
    public static InputStream getInputStreamFromUriString(String uriString, CordovaInterface cordova)
                                                                            ^
  symbol:   class CordovaInterface
  location: class FileHelper
/Users/.../platforms/android/src/org/apache/cordova/camera/FileHelper.java:219: error: cannot find symbol
    public static String getMimeType(String uriString, CordovaInterface cordova) {
                                                       ^
  symbol:   class CordovaInterface
  location: class FileHelper
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:21: error: cannot find symbol
import org.apache.cordova.CallbackContext;
                         ^
  symbol:   class CallbackContext
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:22: error: cannot find symbol
import org.apache.cordova.CordovaInterface;
                         ^
  symbol:   class CordovaInterface
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:23: error: cannot find symbol
import org.apache.cordova.CordovaPlugin;
                         ^
  symbol:   class CordovaPlugin
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:24: error: cannot find symbol
import org.apache.cordova.PluginResult;
                         ^
  symbol:   class PluginResult
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:25: error: cannot find symbol
import org.apache.cordova.CordovaWebView;
                         ^
  symbol:   class CordovaWebView
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:38: error: cannot find symbol
public class NetworkManager extends CordovaPlugin {
                                    ^
  symbol: class CordovaPlugin
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:78: error: cannot find symbol
    private CallbackContext connectionCallbackContext;
            ^
  symbol:   class CallbackContext
  location: class NetworkManager
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:91: error: cannot find symbol
    public void initialize(CordovaInterface cordova, CordovaWebView webView) {
                           ^
  symbol:   class CordovaInterface
  location: class NetworkManager
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:91: error: cannot find symbol
    public void initialize(CordovaInterface cordova, CordovaWebView webView) {
                                                     ^
  symbol:   class CordovaWebView
  location: class NetworkManager
/Users/.../platforms/android/src/org/apache/cordova/networkinformation/NetworkManager.java:121: error: cannot find symbol
    public boolean execute(String action, JSONArray args, CallbackContext callbackContext) {
                                                          ^
  symbol:   class CallbackContext
  location: class NetworkManager
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:27: error: cannot find symbol
import org.apache.cordova.CallbackContext;
                         ^
  symbol:   class CallbackContext
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:28: error: cannot find symbol
import org.apache.cordova.CordovaArgs;
                         ^
  symbol:   class CordovaArgs
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:29: error: cannot find symbol
import org.apache.cordova.CordovaInterface;
                         ^
  symbol:   class CordovaInterface
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:30: error: cannot find symbol
import org.apache.cordova.CordovaPlugin;
                         ^
  symbol:   class CordovaPlugin
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:31: error: cannot find symbol
import org.apache.cordova.CordovaWebView;
                         ^
  symbol:   class CordovaWebView
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:32: error: cannot find symbol
import org.apache.cordova.PluginResult;
                         ^
  symbol:   class PluginResult
  location: package org.apache.cordova
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:35: error: cannot find symbol
public class StatusBar extends CordovaPlugin {
                               ^
  symbol: class CordovaPlugin
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:46: error: cannot find symbol
    public void initialize(final CordovaInterface cordova, CordovaWebView webView) {
                                 ^
  symbol:   class CordovaInterface
  location: class StatusBar
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:46: error: cannot find symbol
    public void initialize(final CordovaInterface cordova, CordovaWebView webView) {
                                                           ^
  symbol:   class CordovaWebView
  location: class StatusBar
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:70: error: cannot find symbol
    public boolean execute(String action, CordovaArgs args, final CallbackContext callbackContext) throws JSONException {
                                          ^
  symbol:   class CordovaArgs
  location: class StatusBar
/Users/.../platforms/android/src/org/apache/cordova/statusbar/StatusBar.java:70: error: cannot find symbol
    public boolean execute(String action, CordovaArgs args, final CallbackContext callbackContext) throws JSONException {
                                                                  ^
  symbol:   class CallbackContext
  location: class StatusBar
/Users/.../platforms/android/src/com/candymedia/wasaclima/CordovaApp.java:27: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/.../platforms/android/src/com/candymedia/wasaclima/CordovaApp.java:30: error: cannot find symbol
        super.onCreate(savedInstanceState);
        ^
  symbol:   variable super
  location: class CordovaApp
/Users/.../platforms/android/src/com/candymedia/wasaclima/CordovaApp.java:31: error: cannot find symbol
        super.init();
        ^
  symbol:   variable super
  location: class CordovaApp
/Users/.../platforms/android/src/com/candymedia/wasaclima/CordovaApp.java:33: error: cannot find symbol
        loadUrl(launchUrl);
                ^
  symbol:   variable launchUrl
  location: class CordovaApp
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:71: error: cannot find symbol
				TextureView textureView = findXWalkTextureView((ViewGroup)webView.getView());
				                                                          ^
  symbol:   variable webView
  location: class Screenshot
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:78: error: cannot find symbol
			View view = cordova.getActivity().getWindow().getDecorView().getRootView();
			            ^
  symbol:   variable cordova
  location: class Screenshot
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:94: error: cannot find symbol
        this.cordova.getActivity().sendBroadcast(mediaScanIntent);
            ^
  symbol: variable cordova
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:98: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:131: error: cannot find symbol
				                        PluginResult result = new PluginResult(PluginResult.Status.OK, jsonRes);
				                        ^
  symbol: class PluginResult
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:131: error: cannot find symbol
				                        PluginResult result = new PluginResult(PluginResult.Status.OK, jsonRes);
				                                                  ^
  symbol: class PluginResult
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:131: error: package PluginResult does not exist
				                        PluginResult result = new PluginResult(PluginResult.Status.OK, jsonRes);
				                                                                           ^
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:108: error: package super does not exist
			super.cordova.getActivity().runOnUiThread(new Runnable() {
			     ^
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:168: error: cannot find symbol
				                   PluginResult result = new PluginResult(PluginResult.Status.OK, jsonRes);
				                   ^
  symbol: class PluginResult
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:168: error: cannot find symbol
				                   PluginResult result = new PluginResult(PluginResult.Status.OK, jsonRes);
				                                             ^
  symbol: class PluginResult
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:168: error: package PluginResult does not exist
				                   PluginResult result = new PluginResult(PluginResult.Status.OK, jsonRes);
				                                                                      ^
/Users/.../platforms/android/src/com/darktalker/cordova/screenshot/Screenshot.java:153: error: package super does not exist
			super.cordova.getActivity().runOnUiThread(new Runnable() {
			     ^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:49: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:51: error: cannot find symbol
    	super.pluginInitialize();
    	^
  symbol:   variable super
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:56: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:61: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:66: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:71: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:73: error: cannot find symbol
		super.setOptions(options);
		^
  symbol:   variable super
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:75: error: cannot find symbol
		if(options.has(OPT_AD_SIZE)) adSize = adSizeFromString(options.optString(OPT_AD_SIZE));
		               ^
  symbol:   variable OPT_AD_SIZE
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:75: error: cannot find symbol
		if(options.has(OPT_AD_SIZE)) adSize = adSizeFromString(options.optString(OPT_AD_SIZE));
		                                                                         ^
  symbol:   variable OPT_AD_SIZE
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:77: error: cannot find symbol
			adSize = new AdSize(adWidth, adHeight);
			                    ^
  symbol:   variable adWidth
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:77: error: cannot find symbol
			adSize = new AdSize(adWidth, adHeight);
			                             ^
  symbol:   variable adHeight
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:83: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:88: error: cannot find symbol
    		PublisherAdView ad = new PublisherAdView(getActivity());
    		                                         ^
  symbol:   method getActivity()
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:94: error: cannot find symbol
            AdView ad = new AdView(getActivity());
                                   ^
  symbol:   method getActivity()
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:102: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:123: error: method does not override or implement a method from a supertype
	@Override
	^
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:126: error: cannot find symbol
        return sz.getWidthInPixels(getActivity());
                                   ^
  symbol:   method getActivity()
  location: class AdMobPlugin
/Users/.../platforms/android/src/com/rjfun/cordova/admob/AdMobPlugin.java:129: error: method does not override or implement a method from a supertype
	@Override
	^
Note: /Users/.../platforms/android/src/nl/xservices/plugins/SocialSharing.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
100 errors
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.004 secs

/Users/.../platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/.../platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/.../platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/.../platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /Users/.../platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)
```

**Comment by Honry** [comment]
I also experienced this issue on cordova android 3.6.3, but it works on cordova android 4.0.0.  I know some API are deprecated on cordova android 4.0.0, and there's only master branch on cordova-screenshot plugin, is it possible to create a branch for cordova android 3.6.3?

**Comment by braianj** [comment]
I've cordova 5.0.0 :(

**Comment by Shizen** [comment]
I'm using Cordova 4.3 and it is not working.

    [javac] ...\platforms\android\src\com\darktalker\cordova\screenshot\Screenshot.java:71: error: cannot find symbol
    [javac] TextureView textureView = findXWalkTextureView((ViewGroup)webView.getView());

**Comment by dbroadhurst** [comment]
I've got the same errors with Cordova 4.3. I'm using 3 other plugins so I know my system setup is working

**Comment by dbroadhurst** [comment]
Found a temp fix for this issue. 

It seems this plugin expects crosswalk to be installed and still tries to call crosswalk functions causing the compile error. I just hacked out the check.


```
/*
		try {
			Class.forName("org.crosswalk.engine.XWalkWebViewEngine");
			isCrosswalk = true;
		} catch (Exception e) {
		}

		if(isCrosswalk) {
			try {

				TextureView textureView = findXWalkTextureView((ViewGroup)webView.getView());
				bitmap = textureView.getBitmap();

			} catch(Exception e) {
			}
		} else {
*/
			View view = cordova.getActivity().getWindow().getDecorView().getRootView();
			view.setDrawingCacheEnabled(true);
			bitmap = Bitmap.createBitmap(view.getDrawingCache());
			view.setDrawingCacheEnabled(false);

//		}

```

**Comment by viskin** [comment]
It should be better to access Crosswalk-specific APIs with reflection, so no compilation issues will occur.

**Comment by gitawego** [comment]
@dbroadhurst for cordova 4.x, please install plugin:
```
cordova plugin add https://github.com/gitawego/cordova-screenshot#v0.1.0
```

**Comment by khasani** [comment]
@braianj

I have the same problem. Did you find a solution for the error: cannot find symbol ?

Thanks in advance

**Comment by braianj** [comment]
I think i make all project again. Installed every plugin again

**Comment by khasani** [comment]
Thanks braianj,

Your solution is OK. I was using Cordova 6.0. I upgrated to 6.1.1 and I had no more errors.

**Comment by jintangWang** [comment]
I fixed it after i update Cordova from 5.3 to 6.2.0 and update other things as follows:

1.  "SDK Platform" for android-23 2.
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)
